# this script will set the pre-conditions for individual galaxies for imagine
import os
import numpy as np


def pre_conditions(par):
    target = par['target']
    project = par['project']
    configuration = par['configuration']

    if target == 'ngc24':
        # NGC 0024                       00h09m56.5s -24d57m47s G         554  0.001848
        phase_cal = '0023-263'
        frequency = 1417.7
        vmin = -50
        nchan = 300
        width = 4
        vel = 554
        line_vmin = 400
        line_vmax = 700
        if project == 'C1528':
            frequency=1384
            phase_cal = '2339-353'
        if project == 'C1179':
            frequency=1344
            phase_cal='2329-384'

    if target == 'ngc45':
        # NGC 0045                       00h14m04.0s -23d10m55s G         467  0.001558
        phase_cal = '0023-263'
        frequency = 1418.2
        vmin = 100
        nchan = 250
        width = 4
        vel = 467
        line_vmin = 350
        line_vmax = 650


    if target == 'ngc625':
        # NGC 0625                       01h35m04.6s -41d26m10s G         396  0.001321
        phase_cal = '0201-440'
        frequency = 1418.2
        vmin = 200
        nchan = 250
        width = 4
        vel = 396
        line_vmin = 300
        line_vmax = 500
        if project == 'C3041':
            frequency = 1418.7
            phase_cal = '0201-440'
            vmin = 250
            nchan = 125
        if project == 'C1545':
            frequency = 1419
            phase_cal = '0153-410'
            vmin = 200
            nchan = 125
        if project == 'C968':
            frequency = 1419
            vmin = 180
            nchan = 125


    if target == 'ngc1433':
        # NGC 1433   03h42m01.5s -47d13m19s G 1076  0.003589
        phase_cal = '0438-436'
        frequency = 1415.2
        alt_freq = 0000
        vmin = 450
        nchan = 300
        width = 4
        vel = 1076
        line_vmin = 950
        line_vmax = 1250



    if target == 'ngc1744':
        # NGC 1744   04h59m57.8s -26d01m20s G 741 0.002472
        phase_cal = '0438-436'
        frequency = 1416.7
        alt_freq = 1419.2
        vmin = 150
        nchan = 300
        width = 4
        vel = 741
        line_vmin = 600
        line_vmax = 900


    if target == 'ngc1792':
        # NGC 1792  05h05m14.4s -37d58m51s G  1211  0.004039
        phase_cal = '0537-441'
        frequency = 1414.7
        alt_freq = 0000
        vmin = 600
        nchan = 300
        width = 4
        vel = 1211
        line_vmin = 1000
        line_vmax = 1400

    if target == 'ngc2835':
        # NGC 2835  09h17m52.9s -22d21m17s G 886  0.002955
        phase_cal = '0859-140'
        frequency = 1416.2
        alt_freq = 0000
        vmin = 300
        nchan = 300
        width = 4
        vel = 886
        line_vmin = 750
        line_vmax = 1150




    if target == 'ngc2997':
        # NGC 2997                       09h45m38.8s -31d11m28s G        1089  0.003633
        phase_cal ='1015-314'
        if project == 'C3157':
            frequency = 1415.2
            alt_freq = 1415.5  # this is an alternative frequency, generated by error due to a block dropout
        if project == 'C1490':
            frequency = 1415
            alt_freq = 1415.5

        vmin = 600
        nchan = 250
        width = 4
        vel = 1089
        line_vmin = 900
        line_vmax = 1300
        #chan_1 = 1.41950
        #chans = 2487
        #chans = 1500
        #increment = -0.000003




    if target == 'ngc3109':
        # NGC 3109  10h03m06.9s -26d09m34s G  403  0.001344
        phase_cal ='1015-314'
        frequency = 1418.2
        alt_freq = 0000  # this is an alternative frequency
        vmin = 100
        nchan = 300
        width = 4
        vel = 403
        line_vmin = 300
        line_vmax = 500


    if target == 'ngc3137':
        # NGC 3137  10h09m07.5s -29d03m52s G 1104  0.003683
        phase_cal ='1015-314'
        frequency = 1415.2
        alt_freq = 0000  # this is an alternative frequency
        vmin = 500
        nchan = 300
        width = 4
        vel = 1104
        line_vmin = 900
        line_vmax = 1300




    if target == 'ngc3511':
        # NGC 3511 11h03m23.8s -23d05m12s G  1109  0.003699
        phase_cal = '1127-145'
        frequency = 1415.2
        alt_freq = 0000  # this is an alternative frequency
        vmin = 500
        nchan = 300
        width = 4
        vel = 1109
        line_vmin = 900
        line_vmax = 1300


    if target == 'ngc7090':
        #NGC 7090  21h36m28.8s -54d33m26s G  847  0.002825
        phase_cal ='0023-263'
        frequency = 1416.2
        alt_freq = 1415.2  # this is an alternative frequency
        vmin = 250
        nchan = 300
        width = 4
        vel = 847
        line_vmin = 650
        line_vmax = 1000

    if target == 'ngc7424':
        #NGC 7424  22h57m18.4s -41d04m14s G  939
        phase_cal ='2259-375'
        frequency = 1415.7
        alt_freq = 0000  # this is an alternative frequency
        vmin = 350
        nchan = 300
        width = 4
        vel = 939
        line_vmin = 800
        line_vmax = 1100


    if target == 'ngc7793':
        #NGC 7793 23h57m49.8s -32d35m28s G    230  0.000767
        phase_cal ='0023-263'
        frequency = 1419.2
        alt_freq = 1419.5  # this is an alternative frequency
        vmin = -400
        nchan = 300
        width = 4
        vel = 230
        line_vmin = 100
        line_vmax = 350


    if target == 'ngc6300':
        # NGC 6300  17h16m59.5s -62d49m14s G 1109  0.003699
        phase_cal ='1814-637'
        frequency = 1415.2
        alt_freq = 0000  # this is an alternative frequency
        vmin = 500
        nchan = 300
        width = 4
        vel = 1109
        line_vmin = 859
        line_vmax = 1350

    if target == 'eso138-010':
        # ESO 138-010  16h59m02.9s -60d12m58s G  1144  0.003816
        phase_cal ='1613-586'
        frequency = 1414.7
        alt_freq = 0000  # this is an alternative frequency
        vmin = 550
        nchan = 300
        width = 4
        vel = 1144
        line_vmin = 1000
        line_vmax = 1300

    if target == 'eso154-023':
        # ESO 154- G 023  02h56m50.4s -54d34m17s G 574
        phase_cal ='0208-512'
        frequency = 1417.7
        vmin = 150
        nchan = 250
        width = 4
        vel = 574
        line_vmin = 470
        line_vmax = 660
        if project == 'C3041':
            phase_cal = '0252-549'
            frequency = 1417.7
            nchan = 200
            if configuration == '15a':
                phase_cal = '0308-611'
            if configuration == 'h168':
                phase_cal = '0407-658'
            if configuration == '750b':
                vmin = 350
                nchan = 100
        if project == 'CX294':
            frequency = 1417.7
            vmin = 254
            nchan = 150
        if project == 'CX062':
            phase_cal ='0252-712'
            frequency = 1417
        if project == 'C1341':
            phase_cal = '0407-658'
            frequency = 1418
            vmin = 150
            nchan = 250





    if target == 'eso214-017':
        # ESO 214- G 017  10h40m18.7s -48d34m11s G 1052  0.003509
        phase_cal ='1215-457'
        frequency = 1415.2
        alt_freq = 0000  # this is an alternative frequency
        vmin = 500
        nchan = 300
        width = 4
        vel = 1052
        line_vmin = 1000
        line_vmax = 1300

    if target == 'eso274-001':
        # ESO 274- G 001 15h14m13.8s -46d48m29s G 522  0.001741 11.7
        phase_cal ='1421-490'
        frequency = 1417.7
        vmin = 200
        nchan = 300
        width = 4
        vel = 522
        line_vmin = 400
        line_vmax = 650



    # rename target name based on atca archival data:
    if target == 'j2052-69': # this is C1341 (LVHIS)
        target == 'ic5052'
    if target == 'ic5052' or target == 'j2052-69':
        # IC 5052  20h52m05.6s -69d12m06s G 584  0.001948
        phase_cal ='1934-638'
        frequency = 1417.7
        if target == 'j2052-69':
            frequency = 1418
        alt_freq = 0000  # this is an alternative frequency
        vmin = 0
        nchan = 300
        width = 4
        vel = 584
        line_vmin = 450
        line_vmax = 750

    if target == 'ic5201':
        # IC 5201   22h20m57.4s -46d02m09s G 915  0.003052
        phase_cal ='2226-411'
        frequency = 1415.7
        vmin = 0
        nchan = 300
        width = 4
        vel = 584
        line_vmin = 915
        line_vmax = 1100



    # on local laptop
    #par['phase_cal'] = phase_cal + '.' + str(int(np.floor(frequency)))
    #par['band_cal1'] = '1934-638' + '.' +  str(int(np.floor(frequency)))
    #par['band_cal2'] = '0823-500' + '.' +  str(int(np.floor(frequency)))
    #par['source'] = par['target'] + '.' +  str(int(np.floor(frequency)))

    par['phase_cal'] = phase_cal + '.' + str(frequency)
    par['band_cal1'] = '1934-638' + '.' +  str(frequency)
    par['band_cal2'] = '0823-500' + '.' +  str(frequency)
    par['source'] = par['target'] + '.' +  str(frequency)

    par['frequency'] = frequency
    par['vmin'] = vmin
    par['nchan'] = nchan
    par['width'] = width
    par['vel'] = vel
    par['line_vmin'] = line_vmin
    par['line_vmax'] = line_vmax


    #return phase_cal, frequency, alt_freq, vmin, nchan, width, vel, line_vmin, line_vmax
    return par
